### ISSUE TITLE
Button click is showing blue background 

### ISSUE THREAD

**Issue by Sivayogeith** [sanskar-soni-9/E-Dictionary#1]
I tested this website in mobile and I saw when clicking the buttons like the play audio button or the dark mode switch changes the background to light blue when pressed. And I maybe think this will work:
 
```css
button {
     -webkit-tap-highlight-color: transparent;
}
```
In `global.scss`

I took this from [utsajan in discord](https://discord.com/channels/1084385709307207782/1084403372490235904/1093156698170073119)
